// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Andrei Baranov (84softworks). Licensed under the Business Source License 1.1 - see LICENSE.
package com.ef_softworks.thundervox_server.sipaccount

import com.ef_softworks.thundervox_server.audit.AuditAction
import com.ef_softworks.thundervox_server.audit.AuditActor
import com.ef_softworks.thundervox_server.audit.AuditLog
import com.ef_softworks.thundervox_server.audit.AuditTargetType
import com.ef_softworks.thundervox_server.config.SipProperties
import com.ef_softworks.thundervox_server.credential.RandomPassword
import com.ef_softworks.thundervox_server.exception.base.WrongTypeException
import com.ef_softworks.thundervox_server.tenant.DefaultTenant
import com.ef_softworks.thundervox_server.util.logInfo
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.stereotype.Component
import org.springframework.transaction.annotation.Transactional
import java.time.LocalDateTime

/**
 * New SIP number for a panel or an app client, from the console or from the operator's backend.
 *
 * The number is generated by default (next free value of the kind's range); an operator may type one instead. The
 * password is generated unless typed, and a generated one is returned exactly once. The account is usable by the
 * core the moment the transaction commits: its subscriber row is written in the same transaction.
 */
@Component
class CreateSipAccount(
    private val sipAccountRepository: SipAccountRepository,
    private val allocateSipNumber: AllocateSipNumber,
    private val subscriberReadModel: SubscriberReadModel,
    private val sipProperties: SipProperties,
    private val defaultTenant: DefaultTenant,
    private val auditLog: AuditLog,
) {

    @Transactional
    fun create(request: CreateSipAccountRequest, actor: AuditActor): SipAccountCredentialsResponse {
        val name = SipAccountInputRules.requireValidName(request.name)

        val externalId = request.externalId?.takeIf { it.isNotBlank() }?.let(SipAccountInputRules::requireValidExternalId)
        if (externalId != null &&
            sipAccountRepository.findByTenantIdAndKindAndExternalId(defaultTenant.id, request.kind, externalId) != null
        ) {
            throw externalIdTaken(request.kind, externalId)
        }

        val requestedNumber = request.username?.takeIf { it.isNotBlank() }?.let(SipAccountInputRules::requireValidNumber)
        if (requestedNumber != null && sipAccountRepository.existsByUsername(requestedNumber)) {
            throw numberTaken(requestedNumber)
        }
        val username = requestedNumber ?: allocateSipNumber.next(request.kind)

        val requestedPassword = request.password?.takeIf { it.isNotEmpty() }
        val generatedPassword = requestedPassword == null
        val password = requestedPassword?.let(SipAccountInputRules::requireValidPassword) ?: RandomPassword.generate()

        val account = SipAccountEntity(
            tenantId = defaultTenant.id,
            username = username,
            realm = sipProperties.realm,
            ha1 = "",
            ha1b = "",
            kind = request.kind,
            name = name,
            externalId = externalId,
        ).apply { setPassword(password, sipProperties.realm) }

        val saved = try {
            sipAccountRepository.saveAndFlush(account)
        } catch (ex: DataIntegrityViolationException) {
            // The same number or the same external id arrived from two requests at once: the unique index decided
            throw if (ex.violatesExternalIdIndex() && externalId != null) externalIdTaken(request.kind, externalId) else numberTaken(username)
        }
        subscriberReadModel.publish(saved)

        auditLog.record(
            actor, AuditAction.SIP_ACCOUNT_CREATED, AuditTargetType.SIP_ACCOUNT, saved.id,
            mapOf(
                "username" to username,
                "name" to name,
                "kind" to request.kind.name,
                "external_id" to externalId,
                "number" to if (requestedNumber == null) "generated" else "set_by_operator",
                "password" to if (generatedPassword) "generated" else "set_by_operator",
            )
        )
        logInfo("SIP account created: username=$username, kind=${request.kind}, external_id=$externalId, by=${actor.login}")
        return SipAccountCredentialsResponse(
            account = SipAccountResponse.from(saved, null, LocalDateTime.now()),
            realm = saved.realm,
            generatedPassword = password.takeIf { generatedPassword },
        )
    }

    private fun numberTaken(username: String) =
        WrongTypeException("SIP number $username is taken", "Номер $username уже занят")
}

internal fun externalIdTaken(kind: SipAccountKind, externalId: String) =
    WrongTypeException("External id $externalId is already bound to another $kind number", "Внешний id $externalId уже привязан к другому номеру")

/** Whether the violated constraint is the external id index rather than the username one (PostgreSQL names it in the message). */
internal fun DataIntegrityViolationException.violatesExternalIdIndex(): Boolean =
    (mostSpecificCause.message ?: "").contains("uq_sip_account_external_id")
